### ISSUE TITLE
Withdrawals from binance to stellar are stuck

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldfoundation/tft#113] opened 2021-06-30 06:34 UTC
```
[31mERROR[0m[06-30|06:32:09.752] failed to get signature from             [31merr[0m="failed to connect to host id '12D3KooWCGiAmE2VLa4hHVhdsEcFRjokKsE3QCDnsqwWCHLHrSC1': failed to find any peer in table"
[31mERROR[0m[06-30|06:32:09.752] failed to create payment for withdrawal to GBRTQBJ7ZER3TXI4ILMXEOT2BNV5A36J73P3GEUO5YDVN5RNPYCNYMKN, required number of signatures is not met 
[31mERROR[0m[06-30|06:32:09.752] failed to create payment for withdrawal to GBRTQBJ7ZER3TXI4ILMXEOT2BNV5A36J73P3GEUO5YDVN5RNPYCNYMKN, required number of signatures is not met 
[32mINFO [0m[06-30|06:32:09.752] Starting withdrawal                      [32mtxHash[0m=aa7ec9…3c18bf
[32mINFO [0m[06-30|06:32:09.753] Creating a withdraw tx                   [32methTx[0m=aa7ec9…3c18bf
[32mINFO [0m[06-30|06:32:09.853] checking if transaction exists           [32mmemo[0m=aa7ec93a2e149ec23b4238d2451ed32aca1f6072f55718b6f059e9ef0a3c18bf
[32mINFO [0m[06-30|06:32:09.854] transaction not found 
[31mERROR[0m[06-30|06:32:09.954] failed to get signature from             [31merr[0m="failed to connect to host id '12D3KooWCGiAmE2VLa4hHVhdsEcFRjokKsE3QCDnsqwWCHLHrSC1': failed to find any peer in table"
[31mERROR[0m[06-30|06:32:09.955] failed to create payment for withdrawal to GB37LECYM3FV2BFTKA3QVGNMS43YTVPZAYK3O6I54A2DXKAOUWVGEH2Y, required number of signatures is not met 
[31mERROR[0m[06-30|06:32:09.955] failed to create payment for withdrawal to GB37LECYM3FV2BFTKA3QVGNMS43YTVPZAYK3O6I54A2DXKAOUWVGEH2Y, required number of signatures is not met 
[32mINFO [0m[06-30|06:32:09.955] Starting withdrawal                      [32mtxHash[0m=6c3f13…ee29e1
[32mINFO [0m[06-30|06:32:09.955] Creating a withdraw tx                   [32methTx[0m=6c3f13…ee29e1
[32mINFO [0m[06-30|06:32:10.056] checking if transaction exists           [32mmemo[0m=6c3f13338d26c9b7733eac6aa7f0710925c073883e23b2ec7b75c728bbee29e1
[32mINFO [0m[06-30|06:32:10.056] transaction not found 
[31mERROR[0m[06-30|06:32:10.157] failed to get signature from             [31merr[0m="failed to connect to host id '12D3KooWCGiAmE2VLa4hHVhdsEcFRjokKsE3QCDnsqwWCHLHrSC1': failed to find any peer in table"
[31mERROR[0m[06-30|06:32:10.157] failed to create payment for withdrawal to GB3H6RFEACES7PXL7YMBSH66HWQN7HX24KDTYAKOD6LI342FTVTWWH6F, required number of signatures is not met 
[31mERROR[0m[06-30|06:32:10.157] failed to create payment for withdrawal to GB3H6RFEACES7PXL7YMBSH66HWQN7HX24KDTYAKOD6LI342FTVTWWH6F, required number of signatures is not met 
[32mINFO [0m[06-30|06:32:10.157] Starting withdrawal                      [32mtxHash[0m=156e7e…02f6dd
[32mINFO [0m[06-30|06:32:10.157] Creating a withdraw tx                   [32methTx[0m=156e7e…02f6dd
[32mINFO [0m[06-30|06:32:10.271] checking if transaction exists           [32mmemo[0m=156e7e151b2b54fa17d3e43eb1939b20013e2f4d7034d6ad3cad95d29102f6dd
[32mINFO [0m[06-30|06:32:10.271] transaction not found 
```

**Comment by sabrinasadik** [comment] 2021-07-01 10:19
Any updates @DylanVerstraete @robvanmieghem ? A lot of messages on the chat

**Comment by DylanVerstraete** [comment] 2021-07-02 12:36
blocked on https://github.com/threefoldfoundation/tft/issues/117

**Comment by robvanmieghem** [comment] 2021-07-03 04:33
It's true that #117 is now the root cause, before it were the timeouts on Stellar. Restarted the cosigner and they are progressing again. Let's not put this in blocked since it might take a while to solve #117, and then this should be marked as duplicate. Closing it for now as it works again, please reopen it if it happens again, I'll have a look once and a while to if manual intervention is needed.

**Closed by robvanmieghem** 2021-07-03 04:33 UTC
Labels: priority_critical
